# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdicionaraluno():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    # Espera entrada do usuário antes de fechar
    input("Pressione Enter para encerrar o navegador...")
    self.driver.quit()
  
  def test_adicionaraluno(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(1920, 1048)
    self.driver.find_element(By.LINK_TEXT, "Adicionar Aluno").click()
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("Luiz")
    self.driver.find_element(By.ID, "nota1").click()
    self.driver.find_element(By.ID, "nota1").send_keys("7.3")
    self.driver.find_element(By.ID, "nota2").click()
    self.driver.find_element(By.ID, "nota2").send_keys("8.2")
    self.driver.find_element(By.ID, "nota3").click()
    self.driver.find_element(By.ID, "nota3").send_keys("7.8")
    self.driver.find_element(By.ID, "nota4").click()
    self.driver.find_element(By.ID, "nota4").send_keys("7.5")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(6)").click()
    print("Teste concluído. Você pode verificar os resultados no navegador.")